### ISSUE TITLE
Must not be accessed before initialization, Laravel Manager

### ISSUE THREAD

**Issue by AndreyDemenenko** [larastan/larastan#1608] opened 2023-03-31 14:28 UTC
- Larastan Version: 9.41.0
- `--level` used: 5
- Pull request with failing test:

### Description
Hello, i receive error after run phpstan analyze, used default configuration from this package documentation

`:$variable must not be accessed before initialization in file /src/app/NameManager.php `

### Laravel code where the issue was found

```php
    protected ?Model $variable;

    public function setVariable(Model $variable): self
    {
        $this->variable = $variable;
  
        return $this;
    }
```
<img width="1586" alt="image" src="https://user-images.githubusercontent.com/105636507/229148473-3b1e6abd-7ca0-45b5-ba6d-c2dee60f0b2f.png">

**Comment by szepeviktor** [comment] 2023-03-31 14:51
Thank you for your report.

Could you share actual source code?

**Comment by AndreyDemenenko** [comment] 2023-03-31 15:13
```php
<?php

namespace App\SpecificBalances;

use App\Models\User;
use Illuminate\Support\Manager;

class SpecificBalanceManager extends Manager
{
    public const BONUS_BALANCE_TYPE = 'BONUS';

    public const MAIN_BALANCE_TYPE = 'main';

    public const ALL_BALANCE_TYPE = 'all';

    public const BALANCE_TYPES = [
        self::BONUS_BALANCE_TYPE,
        self::MAIN_BALANCE_TYPE,
        self::ALL_BALANCE_TYPE,
    ];

    private string $balanceType;


    public function setBalanceType(string $balanceType): static
    {
        if (! in_array($balanceType, static::BALANCE_TYPES)) {
            throw new \Exception("There is no such balance type [{$balanceType}]");
        }

        $this->balanceType = $balanceType;
        return $this;
    }

    public function getDefaultDriver(): string
    {
        return $this->balanceType;
    }

    public function createBonusDriver(): SpecificBalanceManagerContract
    {
        return app(BonusBalanceManager::class);
    }

    public function createMainDriver(): SpecificBalanceManagerContract
    {
        return app(MainBalanceManager::class);
    }

    public function createAllDriver(): SpecificBalanceManagerContract
    {
        return app(AllBalanceManager::class));
    }
}

```

**Comment by szepeviktor** [comment] 2023-03-31 15:40
I think `balanceType` property is not set in the constructor so `getDefaultDriver` could not read it.

Does the error message point to a specific line or is it an "internal error" without line number?

**Comment by AndreyDemenenko** [comment] 2023-03-31 15:42
<img width="1578" alt="image" src="https://user-images.githubusercontent.com/105636507/229167152-e46a28a6-6ec8-47b2-87fe-9bd0f6f22722.png">

same error but from another manager

**Comment by szepeviktor** [comment] 2023-03-31 15:51
This is too hot 🌶️ for me as I'm not a Laravel developer and design patterns in your source code seem to be strange to me.
@canvural may help you describing the root cause.

**Comment by calebdw** [comment] 2024-03-13 03:52
I think this can be closed as there's really nothing for us to do on this end.

> Uncaught Error: Typed property App\OrderProviders\ExternalPanelOrderManager::$type must not be accessed before initialization in /src/app/OrderProviders/ExternalPanelOrderManager.php:30

The problem lies in `/src/app/OrderProviders/ExternalPanelOrderManager.php:30` which is not being shown. Or if it's really being caused by the file being shown then it's because the property is being accessed without first being initialized---the code needs to change

**Closed** 2024-04-14 12:54 UTC
