### ISSUE TITLE
Null given to ObjectType::isSuperTypeOf()

### ISSUE THREAD

**Issue by bytestream** [larastan/larastan#1565] opened 2023-02-28 14:19 UTC
- Larastan Version: 2.4.1
- `--level` used: 8
- Pull request with failing test:

### Description

The use of `random()` results in:
```
Internal error: PHPStan\Type\ObjectType::isSuperTypeOf(): Argument #1 ($type) must be of type PHPStan\Type\Type, null given, called in                                          
     /vendor/nunomaduro/larastan/src/ReturnTypes/CollectionGenericStaticMethodDynamicMethodReturnTypeExtension.php on line 116
```

### Laravel code where the issue was found

```php
/** @var Brand $brand */
$brand = Brand::findOrFail(1);
$department = $brand->groups->random();
```
```php
/** @return BelongsToMany<UserGroup> */
public function groups(): BelongsToMany
{
  return $this->belongsToMany(
    UserGroup::class,
    BrandOperatorGroupMembership::class,
    'brand_id',
    'group_id'
  );
}
```

**Comment by canvural** [comment] 2023-02-28 14:47
Does User Group uses custom collection?

**Comment by canvural** [comment] 2023-03-03 23:12
I cannot reproduce this in the tests. Seems to be working fine even with custom collections.

Can you provide minimal definitions of the models and the relations including any hierarchy? Complete with any PHPDoc used.

**Comment by dododedodonl** [comment] 2023-03-13 10:06
Since updating larastan, I am running into the same problem. I was not able to identify the specific code that triggers the error (there is only a file name), but I was able to identify the version that starts throwing this error.

```
Internal error: Internal error: PHPStan\Type\ObjectType::isSuperTypeOf(): Argument #1 ($type) must be of type PHPStan\Type\Type, null given, called in /vendor/nunomaduro/larastan/src/ReturnTypes/CollectionGenericStaticMethodDynamicMethodReturnTypeExtension.php on line 109 in file
/app/Reports/DataProviders/GeneralDataProvider.php

Post the following stack trace to https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md:
#0 /vendor/nunomaduro/larastan/src/ReturnTypes/CollectionGenericStaticMethodDynamicMethodReturnTypeExtension.php(109): PHPStan\Type\ObjectType->isSuperTypeOf()
#1 /vendor/nunomaduro/larastan/src/ReturnTypes/CollectionGenericStaticMethodDynamicMethodReturnTypeExtension.php(97): NunoMaduro\Larastan\ReturnTypes\CollectionGenericStaticMethodDynamicMethodReturnTypeExtension->handleGenericObjectType()
#2 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(3344): NunoMaduro\Larastan\ReturnTypes\CollectionGenericStaticMethodDynamicMethodReturnTypeExtension->getTypeFromMethodCall()
#3 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1333): PHPStan\Analyser\MutatingScope->methodCallReturnType()
#4 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1339): PHPStan\Analyser\MutatingScope->PHPStan\Analyser\{closure}()
#5 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(556): PHPStan\Analyser\MutatingScope->resolveType()
#6 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1333): PHPStan\Analyser\MutatingScope->getType()
#7 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1339): PHPStan\Analyser\MutatingScope->PHPStan\Analyser\{closure}()
#8 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(556): PHPStan\Analyser\MutatingScope->resolveType()
#9 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1333): PHPStan\Analyser\MutatingScope->getType()
#10 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1339): PHPStan\Analyser\MutatingScope->PHPStan\Analyser\{closure}()
#11 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(556): PHPStan\Analyser\MutatingScope->resolveType()
#12 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1333): PHPStan\Analyser\MutatingScope->getType()
#13 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1339): PHPStan\Analyser\MutatingScope->PHPStan\Analyser\{closure}()
#14 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(556): PHPStan\Analyser\MutatingScope->resolveType()
#15 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1333): PHPStan\Analyser\MutatingScope->getType()
#16 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1339): PHPStan\Analyser\MutatingScope->PHPStan\Analyser\{closure}()
#17 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(556): PHPStan\Analyser\MutatingScope->resolveType()
#18 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1333): PHPStan\Analyser\MutatingScope->getType()
#19 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1339): PHPStan\Analyser\MutatingScope->PHPStan\Analyser\{closure}()
#20 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(556): PHPStan\Analyser\MutatingScope->resolveType()
#21 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Rules/FunctionReturnTypeCheck.php(53): PHPStan\Analyser\MutatingScope->getType()
#22 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Rules/Methods/ReturnTypeRule.php(43): PHPStan\Rules\FunctionReturnTypeCheck->checkReturnType()
#23 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/FileAnalyser.php(106): PHPStan\Rules\Methods\ReturnTypeRule->processNode()
#24 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Node/ClassStatementsGatherer.php(98): PHPStan\Analyser\FileAnalyser->PHPStan\Analyser\{closure}()
#25 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(508): PHPStan\Node\ClassStatementsGatherer->__invoke()
#26 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(417): PHPStan\Analyser\NodeScopeResolver::PHPStan\Analyser\{closure}()
#27 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(362): PHPStan\Analyser\NodeScopeResolver->processStmtNode()
#28 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(523): PHPStan\Analyser\NodeScopeResolver->processStmtNodes()
#29 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(362): PHPStan\Analyser\NodeScopeResolver->processStmtNode()
#30 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(3318): PHPStan\Analyser\NodeScopeResolver->processStmtNodes()
#31 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(3333): PHPStan\Analyser\NodeScopeResolver->processNodesForTraitUse()
#32 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(3329): PHPStan\Analyser\NodeScopeResolver->processNodesForTraitUse()
#33 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(3333): PHPStan\Analyser\NodeScopeResolver->processNodesForTraitUse()
#34 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(3283): PHPStan\Analyser\NodeScopeResolver->processNodesForTraitUse()
#35 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(705): PHPStan\Analyser\NodeScopeResolver->processTraitUse()
#36 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(362): PHPStan\Analyser\NodeScopeResolver->processStmtNode()
#37 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(601): PHPStan\Analyser\NodeScopeResolver->processStmtNodes()
#38 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(362): PHPStan\Analyser\NodeScopeResolver->processStmtNode()
#39 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(573): PHPStan\Analyser\NodeScopeResolver->processStmtNodes()
#40 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(331): PHPStan\Analyser\NodeScopeResolver->processStmtNode()
#41 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/FileAnalyser.php(175): PHPStan\Analyser\NodeScopeResolver->processNodes()
#42 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Command/WorkerCommand.php(130): PHPStan\Analyser\FileAnalyser->analyseFile()
#43 phar:///vendor/phpstan/phpstan/phpstan.phar/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97): PHPStan\Command\WorkerCommand->PHPStan\Command\{closure}()
#44 phar:///vendor/phpstan/phpstan/phpstan.phar/vendor/clue/ndjson-react/src/Decoder.php(110): _PHPStan_1292afebc\Evenement\EventEmitter->emit()
#45 phar:///vendor/phpstan/phpstan/phpstan.phar/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97): _PHPStan_1292afebc\Clue\React\NDJson\Decoder->handleData()
#46 phar:///vendor/phpstan/phpstan/phpstan.phar/vendor/react/stream/src/Util.php(62): _PHPStan_1292afebc\Evenement\EventEmitter->emit()
#47 phar:///vendor/phpstan/phpstan/phpstan.phar/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97): _PHPStan_1292afebc\React\Stream\Util::_PHPStan_1292afebc\React\Stream\{closure}()
#48 phar:///vendor/phpstan/phpstan/phpstan.phar/vendor/react/stream/src/DuplexResourceStream.php(154): _PHPStan_1292afebc\Evenement\EventEmitter->emit()
#49 phar:///vendor/phpstan/phpstan/phpstan.phar/vendor/react/event-loop/src/StreamSelectLoop.php(201): _PHPStan_1292afebc\React\Stream\DuplexResourceStream->handleData()
#50 phar:///vendor/phpstan/phpstan/phpstan.phar/vendor/react/event-loop/src/StreamSelectLoop.php(173): _PHPStan_1292afebc\React\EventLoop\StreamSelectLoop->waitForStreamActivity()
#51 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Command/WorkerCommand.php(96): _PHPStan_1292afebc\React\EventLoop\StreamSelectLoop->run()
#52 phar:///vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Command/Command.php(259): PHPStan\Command\WorkerCommand->execute()
#53 phar:///vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(870): _PHPStan_1292afebc\Symfony\Component\Console\Command\Command->run()
#54 phar:///vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(261): _PHPStan_1292afebc\Symfony\Component\Console\Application->doRunCommand()
#55 phar:///vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(157): _PHPStan_1292afebc\Symfony\Component\Console\Application->doRun()
#56 phar:///vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(124): _PHPStan_1292afebc\Symfony\Component\Console\Application->run()
#57 phar:///vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(125): _PHPStan_1292afebc\{closure}()
#58 /vendor/phpstan/phpstan/phpstan(8): require('...')
#59 /vendor/bin/phpstan(120): include('...')
#60 {main}

```

larastan: 2.5.1
laravel: 9.52.4
larastan level: 5 

I did some digging, and found out the error starts occuring from larastan version 2.3.0.

**Comment by dododedodonl** [comment] 2023-04-18 09:56
@canvural I have been able to narrow it down to the line that causes the issue for me. 

In version 2.3.0 a check was added to [src/ReturnTypes/CollectionGenericStaticMethodDynamicMethodReturnTypeExtension.php](https://github.com/nunomaduro/larastan/blob/0750017b3d3e1bbe3d0342f3777f09d0c19f91a9/src/ReturnTypes/CollectionGenericStaticMethodDynamicMethodReturnTypeExtension.php#L109) line 109. The value of `$genericTypes[0]` is `null` when the error is triggered for me. When adding a `! is_null($genericTypes[0])` check, it stopped throwing errors.

I am not sure how to this should be fixed.

**Comment by TomKita** [comment] 2023-06-19 21:31
I am getting the same issue. I was able to track it down to improper typing in our code that causes the error. 

```
#0 .../vendor/nunomaduro/larastan/src/ReturnTypes/CollectionGenericStaticMethodDynamicMethodReturnTypeExtension.php(109): PHPStan\Type\ObjectType->isSuperTypeOf(NULL)
 #1 .../vendor/nunomaduro/larastan/src/ReturnTypes/CollectionGenericStaticMethodDynamicMethodReturnTypeExtension.php(97): NunoMaduro\Larastan\ReturnTypes\CollectionGenericStaticMethodDynamicMethodReturnTypeExtension->handleGenericObjectType(Object(PHPStan\Reflection\ClassReflection), Object(PHPStan\Reflection\ClassReflection))
 #2 phar://.../vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(3362): NunoMaduro\Larastan\ReturnTypes\CollectionGenericStaticMethodDynamicMethodReturnTypeExtension->getTypeFromMethodCall(Object(PHPStan\Reflection\ResolvedMethodReflection), Object(PhpParser\Node\Expr\MethodCall),
 Object(PHPStan\Analyser\MutatingScope))
 #3 phar://.../vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1351): PHPStan\Analyser\MutatingScope->methodCallReturnType(Object(PHPStan\Type\ObjectType), 'pluck', Object(PhpParser\Node\Expr\MethodCall))
 #4 phar://.../vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1357): PHPStan\Analyser\MutatingScope->PHPStan\Analyser\{closure}()
 #5 phar://.../vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(559): PHPStan\Analyser\MutatingScope->resolveType('$this->items->f...', Object(PhpParser\Node\Expr\MethodCall))
 #6 phar://.../vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1351): PHPStan\Analyser\MutatingScope->getType(Object(PhpParser\Node\Expr\MethodCall))
 #7 phar://.../vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1357): PHPStan\Analyser\MutatingScope->PHPStan\Analyser\{closure}()
 #8 phar://.../vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(559): PHPStan\Analyser\MutatingScope->resolveType('$this->items->f...', Object(PhpParser\Node\Expr\MethodCall))
```

Here is the abstract class the error occurred

```
abstract class TypedCollection extends Collection
{
    protected static string $type;

    public function __construct($items = [])
    {
        foreach ($items as $item) {
            if (! $item instanceof static::$type && ! $item instanceof self) {
                throw new \Exception('Invalid type');
            }
        }

        parent::__construct($items);
    }

    public function offsetSet($key, $value): void
    {
        parent::offsetSet($key, $value);
    }

    public function prepend($value, $key = null)
    {
        if (! $value instanceof static::$type && ! $value instanceof self) {
            throw new \Exception('Invalid type');
        }

        return parent::prepend($value, $key);
    }

    public function push(...$value): static
    {
        foreach ($value as $originalValue) {
            if (! $originalValue instanceof static::$type && ! $originalValue instanceof self) {
                throw new \Exception('Invalid type');
            }

            return parent::push($originalValue);
        }

        return $this;
    }
    public function put($key, $value)
    {
        if (! $value instanceof static::$type && ! $value instanceof self) {
            throw new \Exception('Invalid type');
        }

        return parent::put($key, $value);
    }

    /**
     * Get the values of a given key.
     *
     * @param string      $value
     * @param string|null $key
     *
     * @return static
     */
    public function pluck($value, $key = null)
    {
        return new parent(Arr::pluck($this->items, $value, $key));
    }
}
```

The error happens because of the pluck function and the `static` return type defined in the docblock. When the return type is removed the phpstan error doesn't occur.

**Comment by yamamoto-taku** [comment] 2023-06-26 06:04
I had the same problem with the same error, but when I put "1" in the argument of the random function, the error stopped.

Like this

```
/** @var Brand $brand */
$brand = Brand::findOrFail(1);
$department = $brand->groups->random(1);
```

**Comment by canvural** [comment] 2023-06-26 06:06
I cannot reproduce this. Can someone please open a PR with a failing test?

**Comment by kyrare** [comment] 2023-07-15 12:27
I have this problem too

Occurs with a custom collection class. The problem is in the `\NunoMaduro\Larastan\ReturnTypes\CollectionGenericStaticMethodDynamicMethodReturnTypeExtension::handleGenericObjectType` method, `$genericTypes` is an empty array in my case.

Class for tests:

```
class TestCollection extends Collection
{
    public function map(callable $callback): static
    {
        $keys = array_keys($this->items);

        $items = array_map($callback, $this->items, $keys);

        return new static(array_combine($keys, $items));
    }
    
    public function toArray(): array
    {
        return $this->map(fn($block) => $block->toArray())->values()->all();
    }
}
```

Larvel: 10.15
PHP: 8.2.13
PhpStan: 1.10.25
Larastan: 2.6.3
Level: 0

**Comment by sanfair** [comment] 2023-07-25 14:11
Hi, @bytestream  @dododedodonl, @kyrare 

I'm assuming that all of you are using custom collections. This error occurs if you don't specify an annotation for generics. Here is a quote from the phpstan documentation ([Class-level generics](https://phpstan.org/blog/generics-in-php-using-phpdocs#class-level-generics)):

>When implementing a generic interface or extending a generic class, you have two options:
>
>  * Preserve the genericness of the parent, the child class will also be generic
>  * Specify the type variable of the interface/parent class. The child class will not be generic.

Both of these options require either the `@implements` or `@extends` annotation. If it is not specified, the custom collection will no longer be generic and will not contain any information about the item type.

----

@canvural 
`CollectionGenericStaticMethodDynamicMethodReturnTypeExtension` has a little flaw - it assumes that every collection class is a generic class, which might not be true (possibly because of user error). Error triggers on line 110: 
 https://github.com/nunomaduro/larastan/blob/58636034e8fcb8226254fb6f4b56d30e359d6ef3/src/ReturnTypes/CollectionGenericStaticMethodDynamicMethodReturnTypeExtension.php#L106-L117

This can be easily fixed by next snipped:
```php
if ($genericTypes === []) {
    return new ObjectType($classReflection->getName());
}
```

But I would like that larastan to be able to trigger an error that says explicitly that Custom collection is not a generic class. Is there a way to do it in `CollectionGenericStaticMethodDynamicMethodReturnTypeExtension` or do we need an additional rule for it?

**Closed** 2024-02-20 21:38 UTC
