### ISSUE TITLE
@var tag specifies the type already inferred from source code 

### ISSUE THREAD

**Issue by hmingv** [larastan/larastan#1720] opened 2023-08-17 10:16 UTC
- Larastan Version: 2.6.4
- `--level` used: 9

### Description
When I call the get() method of the Illuminate\Database\Eloquent\Relations class, I need to specify a generic type for the variable assigned to it, otherwise, if I call the map() method, phpstan will prompt me with the following error:
![image](https://github.com/nunomaduro/larastan/assets/57735185/a9a9e26d-6bf8-4737-8c0e-baf2de55914d)

But when I specify a generic type for it, the PHPStorm editor will tell me that it has guessed the type and let me delete `@var`.

When I went to look at the annotations of the get() method, I found that it didn't use `@template` to define the generic type, which caused this problem.
![image](https://github.com/nunomaduro/larastan/assets/57735185/07d9e657-3588-4ce8-a9bd-8b1fb8cb4c50)

I don't know if this is a Laravel problem or if this problem should be solved by Larastan, so I want to ask for some help here.

Thank you so much.

### Laravel code where the issue was found

```php
    public function unreadAll(): JsonResponse
    {
        /** @var Admin $admin */
        $admin         = $this->auth->user();
        /** @var Collection<int, NotificationMessageModel> $notifications */
        $notifications = $admin->unreadNotifications()->get();
        $notifications = $notifications->map(fn (NotificationMessageModel $message) => $this->format($message, false));

        return $this->success(__('Successfully'), compact('notifications'));
    }
```

```php
    /**
     * Get the entity's notifications.
     *
     * @return MorphMany
     */
    public function notifications(): MorphMany
    {
        return $this->morphMany(NotificationMessage::class, 'notifiable')->latest();
    }

    /**
     * Get the entity's unread notifications.
     *
     * @return MorphMany
     */
    public function unreadNotifications(): MorphMany
    {
        return $this->notifications()->unread();
    }
```

**Comment by szepeviktor** [comment] 2023-08-17 10:21
Hello @hmingv!

The template tag comes from Larastan's stubs.

https://github.com/nunomaduro/larastan/blob/9dbd4cf22cae0ca2956ddd4fa797ce97848353e4/stubs/common/Relation.stub#L7-L23

**Comment by szepeviktor** [comment] 2023-08-17 10:23
Adding the related model may help.
```php
    /**
     * Get the entity's unread notifications.
     *
     * @return MorphMany<NotificationMessage>
     */
    public function unreadNotifications(): MorphMany
```

**Comment by hmingv** [comment] 2023-08-17 10:27
Thanks for your reply, but the above method didn't help me, phpstan still says I have the same problem.

```php
        /** @var Collection<int, NotificationMessageModel> $notifications */
        $notifications = $admin->unreadNotifications()->get();
 ```
The above code is valid, but the editor is not friendly
![image](https://github.com/nunomaduro/larastan/assets/57735185/d0f9f946-33a7-49be-8b88-c465c0f505a2)

**Comment by szepeviktor** [comment] 2023-08-17 10:33
```
@var tag specifies the type already inferred from source code
```

Do you think the above statement is untrue?

**Comment by hmingv** [comment] 2023-08-17 10:37
This is the hint given by my editor. It did detect that the return value is a Collection class, but it did not correctly detect that the item in it is a NotificationMessage.

I don't think it's quite right.

Then I tried the following code:

![image](https://github.com/nunomaduro/larastan/assets/57735185/8c031bd7-06c6-4eb8-af7a-b200152cb9d0)

But this time, my editor didn't make any suggestions. The difference between these two pieces of code is that one is an relation query and the other is an ordinary model query.

I'm using PHPStorm.

**Comment by szepeviktor** [comment] 2023-08-17 10:48
I see! So the problem is that PHPStorm needs a hint but Larastan does not.
I do not know how to help you.

**Comment by hmingv** [comment] 2023-08-17 11:14
I created a demo for this

https://github.com/hmingv/demo-for-phpstan

you need to execute

```php
composer install

./vendor/bin/phpstan
```

You can see the error message.

Also, a pleasant surprise, I tested the same code with Laravel 10.x without any problems.

Sorry, forgot to mention, I'm using Laravel 9.x

**Comment by hmingv** [comment] 2023-08-17 11:14
> ... maybe adding Larastan's stubs to PHPStorm???

Since I found Laravel 10.x to be fine, I figured it shouldn't be about PHPStorm.

**Comment by canvural** [comment] 2024-01-02 23:16
Closing as it seems it is not related to Larastan itself.

**Closed by canvural** 2024-01-02 23:16 UTC
